#Week 4: Supervised Learning - Classification - Iris
-------------------------------------
Lab exercise kali ini menggunakan dataset iris:
https://raw.githubusercontent.com/catharinamega/Data-Mining-ISB-2020/main/Week%204/iris.csv

Lakukan klasifikasi pada dataset tersebut dengan menggunakan 3 cara: Logistic Regression, Naive Bayes, dan K-Nearest Neighbor (dengan k=5)

## Import library

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

## Load Dataset

In [33]:
# Read CSV
df = pd.read_csv("https://raw.githubusercontent.com/catharinamega/Data-Mining-ISB-2020/main/Week%204/iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## Data Preprocessing

Periksa apakah ada baris yang duplikat



In [34]:
df.duplicated().any()

True

Periksa apakah ada missing values

In [35]:
df.isnull().any()

sepal_length    False
sepal_width     False
petal_length    False
petal_width     False
species         False
dtype: bool

Periksa outlier dengan boxplot untuk setiap kolom feature

Pisahkan dataset menjadi variabel independen dan variabel dependen

In [36]:
X = df.iloc[:,:-1];
y = df.iloc[:,4];

Pisahkan dataset train dan test dataset, dengan ukuran dataset test 0.1

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, shuffle=True)

Lakukan fitur scaling pada variabel X_train dan X_test. 

In [38]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

#Logistic Regression

Bangun model dan ukur accuracy nya

In [66]:
X_train1, X_test, y_train1, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

Uji model dengan dataset test

In [67]:
classifier = LogisticRegression()
classifier.fit(X_train1, y_train1)
y_pred = classifier.predict(X_test)
print(y_pred)

['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor']


In [68]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix\n", cm)
print("Accuracy Score: ", accuracy_score(y_test, y_pred))

Confusion Matrix
 [[3 0 0]
 [0 8 0]
 [0 0 4]]
Accuracy Score:  1.0


# Naive Bayes

Buat model persamaan berdasarkan data training yang sudah dibuat pada tahap preprocess

In [62]:
model = GaussianNB()
model.fit(X,y)

GaussianNB()

Uji hasil model dengan data test

In [63]:
y_pred = model.predict(X_test)
print(y_pred)

['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor']


Ukur akurasi dari model persamaan Naive Bayes Classifier

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score
cmatrix = confusion_matrix(y_test, y_pred)
print("confusion matrix ", cmatrix)
print("accuracy score", accuracy_score(y_test, y_pred))

confusion matrix  [[3 0 0]
 [0 8 0]
 [0 0 4]]
accuracy score 1.0


# K-Nearest Neighbour (K-NN) Classifier

Buatlah model KNN berdasarkan data training yang sudah dibuat di tahap preprocess, gunakan metric pengukuran jarak 'euclidean'

In [59]:
classifier = KNeighborsClassifier(n_neighbors = 2, metric = "euclidean")
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=2)

Uji model dengan data test

In [60]:
y_predict = classifier.predict(X_test)
print(y_predict)

['virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


Ukur akurasi dari model K-Nearest Neighbor

In [61]:
cmatrix = confusion_matrix(y_test, y_pred)
print("confusion matrix ", cmatrix)
print("accuracy score", accuracy_score(y_test, y_pred))

confusion matrix  [[3 0 0]
 [0 8 0]
 [0 0 4]]
accuracy score 1.0


#Kesimpulan
Dari 3 model klasifikasi di atas (Logistic Regression, Naive Bayes, K-Nearest Neighbor) model klasifikasi dengan akurasi tertinggi adalah...

Dalam Model Klasifikasi dapat dilihat di atas bahwa ketiganya (Logistic Regression, Naive Bayes, K-Nearest Neighbor) memiliki hasil akurasi sempurna yaitu 1.0